### Clean the dataset Movies

In [3]:
import pandas as pd
df = pd.read_csv('Movies.csv')
df.head()

,MovieID,Title,Genres,Language,Country,Total Views
0,1,Toy Story (1995),Animation|Children's|Comedy,German,Italy,69118
1,2,Jumanji (1995),Adventure|Children's|Fantasy,Spanish,UK,1661
2,3,Grumpier Old Men (1995),Comedy|Romance,English,India,22205
3,4,Waiting to Exhale (1995),Comedy|Drama,Spanish,India,84783
4,5,Father of the Bride Part II (1995),Comedy,German,India,61291

In [4]:
df.tail(1)

,MovieID,Title,Genres,Language,Country,Total Views
3882,3952,"Contender, The (2000)",Drama|Thriller,English,USA,27408

In [5]:
df.shape

(3883, 6)

In [6]:
df.dtypes

MovieID         int64
Title          object
Genres         object
Language       object
Country        object
Total Views     int64
dtype: object

In [7]:
## Check for missing values
df.isnull().sum()

MovieID        0
Title          0
Genres         0
Language       0
Country        0
Total Views    0
dtype: int64

In [8]:
## Check for duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
## Check for unique
df.nunique()

MovieID        3883
Title          3883
Genres          304
Language          5
Country           6
Total Views    3824
dtype: int64

In [10]:
##Check the values in Language column and country column
df['Language'].unique()

array(['German', 'Spanish', 'English', 'French', 'Italian'], dtype=object)

In [11]:
#Check the values of country column
df['Country'].unique()

array(['Italy', 'UK', 'India', 'Canada', 'France', 'USA'], dtype=object)

In [12]:
## Statistics of the data
df.describe()

           MovieID   Total Views
count  3883.000000   3883.000000
mean   1986.049446  50382.117435
std    1146.778349  28819.439847
min       1.000000   1062.000000
25%     982.500000  25317.500000
50%    2010.000000  50641.000000
75%    2980.500000  75345.500000
max    3952.000000  99987.000000

In [13]:
## Check for movies that do not have a release year in the title
import re
df[~df['Title'].str.contains(r'\(\d{4}\)', regex=True)]

      MovieID             Title          Genres Language Country  Total Views
15         16  Casino (not_def)  Drama|Thriller   German  France         4961
3866     3936             -1943  Drama|Thriller  English     USA        70804

In [15]:
## Check for missing MovieIDs

expected = set(range(1, df['MovieID'].max() + 1))
actual = set(df['MovieID'])
missing = expected - actual
print(f'Missed ID: {len(missing)}')
print(missing)

Missed ID: 69
{1536, 1540, 646, 1800, 1418, 1802, 1803, 1808, 1530, 1813, 1048, 1560, 1786, 1435, 1691, 1818, 1182, 1823, 1700, 677, 1828, 1576, 1195, 1451, 1452, 686, 1838, 1072, 689, 817, 1074, 1712, 1338, 1469, 323, 1478, 1607, 1736, 1481, 1737, 1229, 1745, 1618, 1491, 1492, 1239, 1751, 91, 221, 1505, 1506, 995, 740, 1634, 1637, 1638, 1512, 1761, 1763, 1766, 3815, 622, 1775, 1521, 1778, 883, 1402, 1403, 1790}