## CLEANING USRE_ID

In [3]:
import pandas as pd
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings_Dataset.csv')
users.head(5)
## ratings.head(5)

  UserID  Age Gender Country SubscriptionStatus  TotalWatchTime    Device
0   SF_1   11      F   India               Free             231    Mobile
1   SF_2   13      M     USA         Subscriber             377  Smart TV
2   SF_3   24      M   Italy               Free             352    Mobile
3   SF_4   37      M     USA         Subscriber             398   Desktop
4   SF_5   15      M      UK         Subscriber             292    Mobile

In [4]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   UserID              6040 non-null   object
 1   Age                 6040 non-null   int64
 2   Gender              6040 non-null   object
 3   Country             6040 non-null   object
 4   SubscriptionStatus  6040 non-null   object
 5   TotalWatchTime      6040 non-null   int64
 6   Device              6040 non-null   object
dtypes: int64(2), object(5)
memory usage: 330.4+ KB

In [6]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RatingID   10000 non-null  int64
 1   UserID     10000 non-null  object
 2   MovieID    10000 non-null  int64
 3   Rating     10000 non-null  float64
 4   Timestamp  10000 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 390.8+ KB

In [7]:
ratings.duplicated().sum()

np.int64(0)

In [8]:
ratings['RatingID'].duplicated().sum()

np.int64(0)

In [9]:
ratings.duplicated(subset=['UserID', 'MovieID']).sum()

np.int64(2)

In [10]:
ratings[ratings.duplicated(subset=['UserID', 'MovieID'], keep=False)]

      RatingID   UserID  MovieID  Rating            Timestamp
1182      1183  SF_1680      824     3.0  2024-01-11 04:32:50
4622      4623  SF_1680      824     3.9  2024-12-09 04:32:50
7936      7937  SF_1756      745     4.3  2024-04-15 04:32:50
8707      8708  SF_1756      745     1.9  2024-02-26 04:32:50

In [11]:
users['Age'].describe()

count    6040.000000
mean       37.207947
std        16.337803
min         9.000000
25%        23.000000
50%        37.000000
75%        51.000000
max        65.000000
Name: Age, dtype: float64

In [14]:
ratings['Timestamp'].describe()

count                   10000
unique                    366
top       2024-02-01 04:32:50
freq                       44
Name: Timestamp, dtype: object